const testContent = {
  ops: [
    { insert: { speaker: "Reene Leas" } },
    { attributes: { start: "0.57", end: "1.2" }, insert: "Kavandatava" },
    { insert: " " },
    { attributes: { start: "1.2", end: "1.83" }, insert: "võimuliidu" },
    { insert: " " },
    { attributes: { start: "1.83", end: "2.4" }, insert: "erakondade" },
    { insert: " " },
    { attributes: { start: "2.4", end: "3.03" }, insert: "volikogud" },
    { insert: " " },
    { attributes: { start: "3.09", end: "3.51" }, insert: "kiitsid" },
    { insert: " " },
    { attributes: { start: "3.51", end: "3.81" }, insert: "heaks" },
    { insert: " " },
    { attributes: { start: "3.81", end: "4.8" }, insert: "koalitsioonileppe" },
    { insert: " " },
    { attributes: { start: "4.83", end: "5.07" }, insert: "ning" },
    { insert: " " },
    {
      attributes: { start: "5.07", end: "6.15" },
      insert: "ministrikandidaadid."
    },
    { insert: " " },
    { attributes: { start: "6.51", end: "7.08" }, insert: "Muuhulgas" },
    { insert: " " },
    { attributes: { start: "7.08", end: "7.35" }, insert: "läheb" },
    { insert: " " },
    { attributes: { start: "7.35", end: "8.22" }, insert: "koalitsioonileppe" },
    { insert: " " },
    { attributes: { start: "8.22", end: "8.49" }, insert: "ette" },
    { insert: " " },
    { attributes: { start: "8.49", end: "8.97" }, insert: "pensioni" },
    { insert: " " },
    { attributes: { start: "8.97", end: "9.27" }, insert: "teise" },
    { insert: " " },
    { attributes: { start: "9.27", end: "9.57" }, insert: "samba" },
    { insert: " " },
    {
      attributes: {
        start: "9.57",
        end: "10.14",
        confidence: "76% kindlust",
        background: "#cce8cc"
      },
      insert: "reformi."
    },
    { insert: " \n" },
    { insert: { speaker: "Helir-Valdor Seeder" } },
    { attributes: { start: "10.29", end: "10.68" }, insert: "Ta" },
    { insert: " " },
    { attributes: { start: "10.68", end: "10.8" }, insert: "on" },
    { insert: " " },
    { attributes: { start: "10.8", end: "11.43" }, insert: "ikka" },
    { insert: " " },
    { attributes: { start: "11.91", end: "12.54" }, insert: "90" },
    { insert: " " },
    { attributes: { start: "12.54", end: "12.96" }, insert: "protsendi" },
    { insert: " " },
    { attributes: { start: "12.96", end: "13.5" }, insert: "ulatuses" },
    { insert: " " },
    { attributes: { start: "13.5", end: "13.8" }, insert: "ka" },
    { insert: " " },
    { attributes: { start: "13.8", end: "14.7" }, insert: "realiseerunud" },
    { insert: " " },
    { attributes: { start: "14.82", end: "15.39" }, insert: "sellisena," },
    { insert: " " },
    { attributes: { start: "15.39", end: "15.81" }, insert: "nagu" },
    { insert: " " },
    { attributes: { start: "16.11", end: "16.32" }, insert: "meie" },
    { insert: " " },
    { attributes: { start: "16.32", end: "16.53" }, insert: "seda" },
    { insert: " " },
    { attributes: { start: "16.53", end: "17.1" }, insert: "soovisime," },
    { insert: " " },
    { attributes: { start: "17.1", end: "17.37" }, insert: "päris" },
    { insert: " " },
    { attributes: { start: "17.37", end: "17.79" }, insert: "täpselt" },
    { insert: " " },
    {
      attributes: { start: "17.79", end: "18.78" },
      insert: "koalitsioonilepingus"
    },
    { insert: " " },
    { attributes: { start: "18.93", end: "19.26" }, insert: "lahti" },
    { insert: " " },
    { attributes: { start: "19.26", end: "20.01" }, insert: "kirjutatud." },
    { insert: "\n" },
    { insert: { speaker: "Reene Leas" } },
    { attributes: { start: "21.04", end: "21.52" }, insert: "USA" },
    { insert: " " },
    { attributes: { start: "21.52", end: "22.27" }, insert: "lennukitootja" },
    { insert: " " },
    { attributes: { start: "22.27", end: "22.78" }, insert: "Boeing" },
    { insert: " " },
    { attributes: { start: "22.78", end: "23.26" }, insert: "vähendab" },
    { insert: " " },
    { attributes: { start: "23.26", end: "24.04" }, insert: "lennukitüübi" },
    { insert: " " },
    { attributes: { start: "24.04", end: "24.4" }, insert: "seitse," },
    { insert: " " },
    { attributes: { start: "24.4", end: "24.64" }, insert: "kolm," },
    { insert: " " },
    { attributes: { start: "24.64", end: "25.06" }, insert: "seitse" },
    { insert: " " },
    { attributes: { start: "25.06", end: "25.45" }, insert: "maks" },
    { insert: " " },
    { attributes: { start: "25.48", end: "26.08" }, insert: "tootmist" },
    { insert: " " },
    { attributes: { start: "26.53", end: "26.95" }, insert: "Iraani" },
    { insert: " " },
    {
      attributes: {
        start: "26.95",
        end: "27.4",
        confidence: "79% kindlust",
        background: "#cce8cc"
      },
      insert: "võimude"
    },
    { insert: " " },
    { attributes: { start: "27.4", end: "28.21" }, insert: "evakueerivad" },
    { insert: " " },
    { attributes: { start: "28.21", end: "28.69" }, insert: "tulvade" },
    { insert: " " },
    { attributes: { start: "28.69", end: "29.05" }, insert: "eest" },
    { insert: " " },
    { attributes: { start: "29.11", end: "29.44" }, insert: "riigi" },
    { insert: " " },
    { attributes: { start: "29.44", end: "30.19" }, insert: "edelaosas" },
    { insert: " " },
    { attributes: { start: "30.22", end: "30.52" }, insert: "veel" },
    { insert: " " },
    { attributes: { start: "30.52", end: "30.79" }, insert: "neli" },
    { insert: " " },
    { attributes: { start: "30.79", end: "31.21" }, insert: "linna." },
    { insert: " " },
    { attributes: { start: "31.87", end: "32.17" }, insert: "Täna" },
    { insert: " " },
    { attributes: { start: "32.17", end: "32.65" }, insert: "algas" },
    { insert: " " },
    { attributes: { start: "32.65", end: "32.95" }, insert: "taas" },
    { insert: " " },
    { attributes: { start: "32.95", end: "33.64" }, insert: "veteranide" },
    { insert: " " },
    { attributes: { start: "33.64", end: "34.21" }, insert: "toetuseks" },
    { insert: " " },
    { attributes: { start: "34.21", end: "34.63" }, insert: "mõeldud" },
    { insert: " " },
    {
      attributes: { start: "34.63", end: "36.01" },
      insert: "heategevuskampaania"
    },
    { insert: " " },
    { attributes: { start: "36.01", end: "36.43" }, insert: "Anname" },
    { insert: " " },
    { attributes: { start: "36.43", end: "36.73" }, insert: "Au." },
    { insert: " \n" },
    { insert: { speaker: "Helir-Valdor Seeder" } },
    { attributes: { start: "37.11", end: "37.47" }, insert: "Need" },
    { insert: " " },
    { attributes: { start: "37.47", end: "37.98" }, insert: "teod" },
    { insert: " " },
    { attributes: { start: "38.04", end: "38.22" }, insert: "ja" },
    { insert: " " },
    { attributes: { start: "38.22", end: "38.37" }, insert: "need" },
    { insert: " " },
    { attributes: { start: "38.37", end: "39.03" }, insert: "panused," },
    { insert: " " },
    { attributes: { start: "39.09", end: "39.27" }, insert: "mis" },
    { insert: " " },
    { attributes: { start: "39.27", end: "39.39" }, insert: "nad" },
    { insert: " " },
    { attributes: { start: "39.39", end: "39.6" }, insert: "on" },
    { insert: " " },
    { attributes: { start: "39.6", end: "40.17" }, insert: "andnud" },
    { insert: " " },
    { attributes: { start: "40.26", end: "40.71" }, insert: "Eesti" },
    { insert: " " },
    { attributes: { start: "40.71", end: "41.34" }, insert: "eest." },
    { insert: " " },
    { attributes: { start: "41.79", end: "42" }, insert: "Me" },
    { insert: " " },
    { attributes: { start: "42", end: "42.78" }, insert: "väärtustame" },
    { insert: " " },
    { attributes: { start: "42.78", end: "43.23" }, insert: "neid," },
    { insert: " " },
    { attributes: { start: "43.68", end: "43.95" }, insert: "et" },
    { insert: " " },
    { attributes: { start: "43.95", end: "44.25" }, insert: "nende" },
    { insert: " " },
    { attributes: { start: "44.28", end: "44.94" }, insert: "tervis" },
    { insert: " " },
    { attributes: { start: "45", end: "45.39" }, insert: "saaks" },
    { insert: " " },
    { attributes: { start: "45.39", end: "46.29" }, insert: "taastatud" },
    { insert: " " },
    { attributes: { start: "46.68", end: "46.98" }, insert: "ja" },
    { insert: " " },
    { attributes: { start: "47.04", end: "47.25" }, insert: "et" },
    { insert: " " },
    { attributes: { start: "47.25", end: "47.55" }, insert: "nende" },
    { insert: " " },
    { attributes: { start: "47.55", end: "48.42" }, insert: "lähedased" },
    { insert: " " },
    { attributes: { start: "48.57", end: "49.05" }, insert: "saaksid" },
    { insert: " " },
    { attributes: { start: "49.05", end: "49.59" }, insert: "vajalikku" },
    { insert: " " },
    { attributes: { start: "49.59", end: "49.95" }, insert: "abi." },
    { insert: " \n" },
    { insert: { speaker: "Reene Leas" } },
    { attributes: { start: "50.97", end: "51.3" }, insert: "Täna" },
    { insert: " " },
    { attributes: { start: "51.3", end: "51.66" }, insert: "lõpeb" },
    { insert: " " },
    { attributes: { start: "51.66", end: "52.29" }, insert: "Tallinnas" },
    { insert: " " },
    { attributes: { start: "52.35", end: "52.83" }, insert: "meeste" },
    { insert: " " },
    { attributes: { start: "52.86", end: "53.49" }, insert: "korvpalli" },
    { insert: " " },
    { attributes: { start: "53.49", end: "54.18" }, insert: "Eesti-Läti" },
    { insert: " " },
    { attributes: { start: "54.18", end: "54.96" }, insert: "ühisliiga" },
    { insert: " " },
    { attributes: { start: "54.96", end: "55.41" }, insert: "esimene" },
    { insert: " " },
    { attributes: { start: "55.41", end: "55.92" }, insert: "hooaeg." },
    { insert: " " },
    { attributes: { start: "56.22", end: "56.67" }, insert: "Ainsa" },
    { insert: " " },
    { attributes: { start: "56.67", end: "56.97" }, insert: "Eesti" },
    { insert: " " },
    { attributes: { start: "56.97", end: "57.45" }, insert: "klubina" },
    { insert: " " },
    { attributes: { start: "57.45", end: "57.78" }, insert: "nelja" },
    { insert: " " },
    { attributes: { start: "57.78", end: "58.14" }, insert: "parema" },
    { insert: " " },
    { attributes: { start: "58.14", end: "58.53" }, insert: "hulka" },
    { insert: " " },
    { attributes: { start: "58.53", end: "58.95" }, insert: "jõudnud" },
    { insert: " " },
    { attributes: { start: "58.95", end: "59.28" }, insert: "Kalev" },
    { insert: " " },
    { attributes: { start: "59.28", end: "59.76" }, insert: "Cramo" },
    { insert: " " },
    { attributes: { start: "59.82", end: "60.15" }, insert: "mängib" },
    { insert: " " },
    { attributes: { start: "60.15", end: "60.6" }, insert: "praegu" },
    { insert: " " },
    {
      attributes: { start: "60.63", end: "61.59" },
      insert: "pronksikohtumist."
    },
    { insert: " " },
    { attributes: { start: "62.19", end: "62.52" }, insert: "Homne" },
    { insert: " " },
    { attributes: { start: "62.52", end: "62.82" }, insert: "ilm" },
    { insert: " " },
    { attributes: { start: "62.82", end: "63.15" }, insert: "tuleb" },
    { insert: " " },
    { attributes: { start: "63.15", end: "63.57" }, insert: "muutliku" },
    { insert: " " },
    { attributes: { start: "63.57", end: "64.32" }, insert: "pilvisusega," },
    { insert: " " },
    { attributes: { start: "64.41", end: "65.19" }, insert: "õhtupoolikul" },
    { insert: " " },
    { attributes: { start: "65.19", end: "65.46" }, insert: "sajab" },
    { insert: " " },
    { attributes: { start: "65.46", end: "65.82" }, insert: "kohati" },
    { insert: " " },
    { attributes: { start: "65.82", end: "66.15" }, insert: "vähest" },
    { insert: " " },
    { attributes: { start: "66.15", end: "66.57" }, insert: "vihma." },
    { insert: " " },
    { attributes: { start: "66.96", end: "67.89" }, insert: "Õhutemperatuur" },
    { insert: " " },
    { attributes: { start: "67.89", end: "68.01" }, insert: "on" },
    { insert: " " },
    { attributes: { start: "68.01", end: "68.43" }, insert: "kaheksa" },
    { insert: " " },
    { attributes: { start: "68.43", end: "68.61" }, insert: "kuni" },
    { insert: " " },
    { attributes: { start: "68.61", end: "69.21" }, insert: "13," },
    { insert: " " },
    { attributes: { start: "69.27", end: "69.81" }, insert: "rannikul" },
    { insert: " " },
    { attributes: { start: "69.84", end: "70.11" }, insert: "kuus" },
    { insert: " " },
    { attributes: { start: "70.11", end: "70.56" }, insert: "kraadi." },
    { insert: " \n" },
    { attributes: { start: "76.85", end: "77.81" }, insert: "Keskerakonna" },
    { insert: " " },
    { attributes: { start: "77.84", end: "78.2" }, insert: "Eesti" },
    { insert: " " },
    { attributes: { start: "78.2", end: "79.19" }, insert: "Konservatiivse" },
    { insert: " " },
    { attributes: { start: "79.19", end: "80.09" }, insert: "Rahvaerakonna" },
    { insert: " " },
    { attributes: { start: "80.12", end: "80.39" }, insert: "ning" },
    { insert: " " },
    { attributes: { start: "80.39", end: "80.81" }, insert: "Isamaa" },
    { insert: " " },
    { attributes: { start: "80.81", end: "81.47" }, insert: "volikogud" },
    { insert: " " },
    { attributes: { start: "81.53", end: "82.25" }, insert: "kinnitasid" },
    { insert: " " },
    { attributes: { start: "82.25", end: "82.73" }, insert: "loodava" },
    { insert: " " },
    { attributes: { start: "82.73", end: "83.36" }, insert: "võimuliidu" },
    { insert: " " },
    { attributes: { start: "83.36", end: "83.84" }, insert: "leppe" },
    { insert: " " },
    { attributes: { start: "83.87", end: "84.2" }, insert: "ning" },
    { insert: " " },
    {
      attributes: { start: "84.23", end: "85.4" },
      insert: "ministrikandidaadid."
    },
    { insert: " " },
    { attributes: { start: "85.91", end: "86.54" }, insert: "Erakonnad" },
    { insert: " " },
    { attributes: { start: "86.54", end: "87.32" }, insert: "allkirjastavad" },
    { insert: " " },
    { attributes: { start: "87.32", end: "88.25" }, insert: "36-le" },
    { insert: " " },
    { attributes: { start: "88.25", end: "88.94" }, insert: "leheküljele" },
    { insert: " " },
    { attributes: { start: "88.94", end: "89.27" }, insert: "kirja" },
    { insert: " " },
    { attributes: { start: "89.27", end: "89.63" }, insert: "pandud" },
    { insert: " " },
    {
      attributes: { start: "89.63", end: "90.71" },
      insert: "koalitsioonilepingu."
    },
    { insert: " " },
    { attributes: { start: "90.71", end: "91.4" }, insert: "Esmaspäeval" },
    { insert: " " },
    { attributes: { start: "91.79", end: "92.21" }, insert: "jätkab" },
    { insert: " " },
    { attributes: { start: "92.24", end: "92.54" }, insert: "Janek" },
    { insert: " " },
    { attributes: { start: "92.54", end: "92.9" }, insert: "Salme." },
    { insert: " \n" },
    { insert: { speaker: "Janek Salme" } },
    { attributes: { start: "93.72", end: "94.29" }, insert: "Loodavas" },
    { insert: " " },
    { attributes: { start: "94.29", end: "94.77" }, insert: "valitsuses" },
    { insert: " " },
    { attributes: { start: "94.77", end: "95.07" }, insert: "jätkab" },
    { insert: " " },
    { attributes: { start: "95.07", end: "95.88" }, insert: "peaministrina" },
    { insert: " " },
    { attributes: { start: "95.94", end: "96.57" }, insert: "Keskerakonna" },
    { insert: " " },
    { attributes: { start: "96.57", end: "96.96" }, insert: "esimees" },
    { insert: " " },
    { attributes: { start: "97.02", end: "97.29" }, insert: "Jüri" },
    { insert: " " },
    { attributes: { start: "97.29", end: "97.68" }, insert: "Ratas." },
    { insert: " " },
    { attributes: { start: "98.06", end: "98.87" }, insert: "Keskerakonna" },
    { insert: " " },
    { attributes: { start: "98.87", end: "99.35" }, insert: "kandidaat" },
    { insert: " " },
    { attributes: { start: "99.35", end: "99.71" }, insert: "haridus" },
    { insert: " " },
    { attributes: { start: "99.71", end: "99.92" }, insert: "ja" },
    { insert: " " },
    {
      attributes: { start: "99.92", end: "101" },
      insert: "teadusministrikohale"
    },
    { insert: " " },
    { attributes: { start: "101", end: "101.21" }, insert: "on" },
    { insert: " " },
    { attributes: { start: "101.27", end: "101.63" }, insert: "Mailis" },
    { insert: " " },
    { attributes: { start: "101.66", end: "101.99" }, insert: "Reps" },
    { insert: " " },
    { attributes: { start: "102.14", end: "102.59" }, insert: "majandus" },
    { insert: " " },
    { attributes: { start: "102.59", end: "102.77" }, insert: "ja" },
    { insert: " " },
    {
      attributes: { start: "102.77", end: "103.55" },
      insert: "taristuministri"
    },
    { insert: " " },
    { attributes: { start: "103.55", end: "104.03" }, insert: "ametisse" },
    { insert: " " },
    { attributes: { start: "104.03", end: "104.33" }, insert: "Taavi" },
    { insert: " " },
    { attributes: { start: "104.33", end: "104.6" }, insert: "Aas" },
    { insert: " " },
    {
      attributes: { start: "105.11", end: "106.25" },
      insert: "regionaalministrikohale"
    },
    { insert: " " },
    { attributes: { start: "106.25", end: "106.52" }, insert: "Jaak" },
    { insert: " " },
    { attributes: { start: "106.52", end: "106.82" }, insert: "Aabi" },
    { insert: " " },
    { attributes: { start: "106.82", end: "107" }, insert: "ja" },
    { insert: " " },
    {
      attributes: { start: "107", end: "108.32" },
      insert: "sotsiaalministriametisse"
    },
    { insert: " " },
    { attributes: { start: "108.35", end: "108.68" }, insert: "Tanel" },
    { insert: " " },
    { attributes: { start: "108.68", end: "109.07" }, insert: "Kiik." },
    { insert: " " },
    {
      attributes: { start: "109.62", end: "110.55" },
      insert: "Konservatiivse"
    },
    { insert: " " },
    { attributes: { start: "110.55", end: "111.15" }, insert: "Rahvaerakonna" },
    { insert: " " },
    { attributes: { start: "111.15", end: "111.66" }, insert: "kandidaat." },
    { insert: " " },
    {
      attributes: { start: "111.69", end: "112.77" },
      insert: "Siseministriametisse"
    },
    { insert: " " },
    { attributes: { start: "112.77", end: "112.95" }, insert: "on" },
    { insert: " " },
    { attributes: { start: "113.01", end: "113.28" }, insert: "Mart" },
    { insert: " " },
    { attributes: { start: "113.28", end: "113.7" }, insert: "Helme," },
    { insert: " " },
    {
      attributes: { start: "113.82", end: "115.11" },
      insert: "rahandusministrikandidaat"
    },
    { insert: " " },
    { attributes: { start: "115.14", end: "115.53" }, insert: "Martin" },
    { insert: " " },
    { attributes: { start: "115.53", end: "115.89" }, insert: "Helme," },
    { insert: " " },
    {
      attributes: { start: "116.31", end: "117.66" },
      insert: "keskkonnaministrikandidaat"
    },
    { insert: " " },
    { attributes: { start: "117.72", end: "117.99" }, insert: "Rene" },
    { insert: " " },
    {
      attributes: { start: "117.99", end: "119.76" },
      insert: "Kokkmaaeluministrikandidaat,"
    },
    { insert: " " },
    { attributes: { start: "119.79", end: "120.06" }, insert: "Mart" },
    { insert: " " },
    { attributes: { start: "120.06", end: "120.42" }, insert: "Järvik" },
    { insert: " " },
    { attributes: { start: "120.42", end: "120.69" }, insert: "ning" },
    { insert: " " },
    {
      attributes: { start: "120.72", end: "121.44" },
      insert: "väliskaubandus"
    },
    { insert: " " },
    { attributes: { start: "121.44", end: "121.68" }, insert: "ja" },
    { insert: " " },
    {
      attributes: { start: "121.74", end: "122.94" },
      insert: "IT-ministrikandidaat"
    },
    { insert: " " },
    { attributes: { start: "123", end: "123.33" }, insert: "Marti" },
    { insert: " " },
    { attributes: { start: "123.33", end: "123.78" }, insert: "Kuusik." },
    { insert: " " },
    { attributes: { start: "124.59", end: "124.92" }, insert: "Isamaa" },
    { insert: " " },
    { attributes: { start: "124.92", end: "125.25" }, insert: "esitab" },
    { insert: " " },
    {
      attributes: { start: "125.25", end: "126.06" },
      insert: "kaitseministriks"
    },
    { insert: " " },
    { attributes: { start: "126.09", end: "126.33" }, insert: "Jüri" },
    { insert: " " },
    { attributes: { start: "126.33", end: "126.72" }, insert: "Luige" },
    { insert: " " },
    {
      attributes: { start: "126.81", end: "127.8" },
      insert: "justiitsministriks"
    },
    { insert: " " },
    { attributes: { start: "127.83", end: "128.16" }, insert: "Raivo" },
    { insert: " " },
    {
      attributes: {
        start: "128.16",
        end: "128.55",
        confidence: "84% kindlust",
        background: "#cce8cc"
      },
      insert: "Aegi,"
    },
    { insert: " " },
    {
      attributes: { start: "128.9", end: "129.65" },
      insert: "välisministriks"
    },
    { insert: " " },
    { attributes: { start: "129.68", end: "130.01" }, insert: "Urmas" },
    { insert: " " },
    { attributes: { start: "130.01", end: "130.55" }, insert: "Reinsalu," },
    { insert: " " },
    {
      attributes: { start: "130.61", end: "131.57" },
      insert: "kultuuriministriks"
    },
    { insert: " " },
    { attributes: { start: "131.66", end: "131.93" }, insert: "Tõnis" },
    { insert: " " },
    { attributes: { start: "131.93", end: "132.38" }, insert: "Lukase" },
    { insert: " " },
    { attributes: { start: "132.38", end: "132.62" }, insert: "ja" },
    { insert: " " },
    {
      attributes: { start: "132.68", end: "133.76" },
      insert: "rahvastikuministriks"
    },
    { insert: " " },
    {
      attributes: {
        start: "133.82",
        end: "134.18",
        confidence: "43% kindlust",
        background: "#ffff66"
      },
      insert: "Rinas."
    },
    { insert: " " },
    { attributes: { start: "134.18", end: "134.57" }, insert: "Holmani" },
    { insert: " " },
    { attributes: { start: "135.38", end: "135.95" }, insert: "Keskerakonna" },
    { insert: " " },
    { attributes: { start: "135.95", end: "136.28" }, insert: "esimees" },
    { insert: " " },
    { attributes: { start: "136.31", end: "136.55" }, insert: "Jüri" },
    { insert: " " },
    { attributes: { start: "136.55", end: "136.85" }, insert: "Ratas" },
    { insert: " " },
    { attributes: { start: "136.85", end: "137.12" }, insert: "ütles" },
    { insert: " " },
    {
      attributes: { start: "137.15", end: "137.99" },
      insert: "erakonnakaaslaste"
    },
    { insert: " " },
    { attributes: { start: "137.99", end: "138.17" }, insert: "ees" },
    { insert: " " },
    { attributes: { start: "138.17", end: "138.5" }, insert: "peetud" },
    { insert: " " },
    { attributes: { start: "138.5", end: "138.77" }, insert: "kõnes," },
    { insert: " " },
    { attributes: { start: "138.77", end: "138.98" }, insert: "et" },
    { insert: " " },
    { attributes: { start: "139.01", end: "139.34" }, insert: "loodav" },
    { insert: " " },
    { attributes: { start: "139.34", end: "140" }, insert: "valitsusliit" },
    { insert: " " },
    { attributes: { start: "140", end: "140.33" }, insert: "hakkab" },
    { insert: " " },
    { attributes: { start: "140.33", end: "140.72" }, insert: "tööle" },
    { insert: " " },
    { attributes: { start: "140.78", end: "141.11" }, insert: "Eesti" },
    { insert: " " },
    { attributes: { start: "141.11", end: "141.65" }, insert: "tervikliku" },
    { insert: " " },
    { attributes: { start: "141.65", end: "141.98" }, insert: "arengu" },
    { insert: " " },
    { attributes: { start: "141.98", end: "142.28" }, insert: "nimel" },
    { insert: " " },
    { attributes: { start: "142.31", end: "142.49" }, insert: "ning" },
    { insert: " " },
    { attributes: { start: "142.49", end: "142.85" }, insert: "seisab" },
    { insert: " " },
    { attributes: { start: "142.88", end: "143.15" }, insert: "iga" },
    { insert: " " },
    { attributes: { start: "143.15", end: "143.6" }, insert: "inimese" },
    { insert: " " },
    { attributes: { start: "143.66", end: "144.08" }, insert: "heaolu" },
    { insert: " " },
    { attributes: { start: "144.08", end: "144.38" }, insert: "eest." },
    { insert: " \n" },
    { insert: { speaker: "Jüri Ratas" } },
    { attributes: { start: "144.51", end: "144.72" }, insert: "Ja" },
    { insert: " " },
    { attributes: { start: "144.72", end: "144.87" }, insert: "kui" },
    { insert: " " },
    { attributes: { start: "144.87", end: "145.29" }, insert: "mõelda" },
    { insert: " " },
    { attributes: { start: "145.29", end: "145.95" }, insert: "sellele" },
    { insert: " " },
    { attributes: { start: "146.28", end: "147.18" }, insert: "loodavale" },
    { insert: " " },
    {
      attributes: { start: "147.66", end: "148.77" },
      insert: "koalitsioonile"
    },
    { insert: " " },
    { attributes: { start: "149.82", end: "150.12" }, insert: "siis" },
    { insert: " " },
    { attributes: { start: "150.12", end: "150.39" }, insert: "minu" },
    { insert: " " },
    { attributes: { start: "150.39", end: "150.99" }, insert: "meelest" },
    { insert: " " },
    { attributes: { start: "151.92", end: "152.13" }, insert: "see" },
    { insert: " " },
    { attributes: { start: "152.13", end: "152.22" }, insert: "on" },
    { insert: " " },
    { attributes: { start: "152.22", end: "153" }, insert: "oluline" },
    { insert: " " },
    { attributes: { start: "153.33", end: "153.51" }, insert: "on" },
    { insert: " " },
    { attributes: { start: "153.51", end: "153.84" }, insert: "kolm" },
    { insert: " " },
    { attributes: { start: "153.84", end: "154.44" }, insert: "märksõna." },
    { insert: " " },
    { attributes: { start: "155.31", end: "155.49" }, insert: "See" },
    { insert: " " },
    { attributes: { start: "155.49", end: "155.61" }, insert: "on" },
    { insert: " " },
    { attributes: { start: "155.61", end: "155.94" }, insert: "see," },
    { insert: " " },
    { attributes: { start: "155.94", end: "156.09" }, insert: "et" },
    { insert: " " },
    { attributes: { start: "156.09", end: "156.75" }, insert: "Eestimaal" },
    { insert: " " },
    { attributes: { start: "156.75", end: "157.26" }, insert: "oleks" },
    { insert: " " },
    { attributes: { start: "157.95", end: "158.76" }, insert: "heaolu." },
    { insert: " " },
    { attributes: { start: "159.42", end: "159.66" }, insert: "Et" },
    { insert: " " },
    { attributes: { start: "159.66", end: "160.26" }, insert: "Eestimaal" },
    { insert: " " },
    { attributes: { start: "160.26", end: "160.8" }, insert: "oleks" },
    { insert: " " },
    { attributes: { start: "161.46", end: "162.45" }, insert: "lasterikkus" },
    { insert: " " },
    { attributes: { start: "162.78", end: "162.9" }, insert: "ja" },
    { insert: " " },
    { attributes: { start: "162.9", end: "163.02" }, insert: "et" },
    { insert: " " },
    { attributes: { start: "163.02", end: "163.5" }, insert: "Eestimaal" },
    { insert: " " },
    { attributes: { start: "163.5", end: "163.98" }, insert: "oleks" },
    { insert: " " },
    { attributes: { start: "164.37", end: "165.15" }, insert: "koostöö." },
    { insert: " " },
    { attributes: { start: "166.05", end: "166.38" }, insert: "Kõik" },
    { insert: " " },
    { attributes: { start: "166.38", end: "166.59" }, insert: "need" },
    { insert: " " },
    { attributes: { start: "166.59", end: "167.16" }, insert: "hirmud," },
    { insert: " " },
    { attributes: { start: "167.79", end: "168.06" }, insert: "mida" },
    { insert: " " },
    { attributes: { start: "168.06", end: "168.15" }, insert: "on" },
    { insert: " " },
    { attributes: { start: "168.15", end: "168.72" }, insert: "ühiskonda" },
    { insert: " " },
    { attributes: { start: "168.72", end: "169.35" }, insert: "külvatud." },
    { insert: " " },
    { attributes: { start: "170.16", end: "170.4" }, insert: "Et" },
    { insert: " " },
    { attributes: { start: "170.4", end: "171.24" }, insert: "pööratakse" },
    { insert: " " },
    { attributes: { start: "171.27", end: "172.11" }, insert: "tagasi" },
    { insert: " " },
    { attributes: { start: "172.53", end: "172.95" }, insert: "üks," },
    { insert: " " },
    { attributes: { start: "172.95", end: "173.37" }, insert: "teine" },
    { insert: " " },
    { attributes: { start: "173.37", end: "173.52" }, insert: "või" },
    { insert: " " },
    { attributes: { start: "173.52", end: "174" }, insert: "kolmas" },
    { insert: " " },
    { attributes: { start: "174", end: "174.42" }, insert: "asi" },
    { insert: " " },
    { attributes: { start: "174.79", end: "174.94" }, insert: "või" },
    { insert: " " },
    { attributes: { start: "174.94", end: "175.54" }, insert: "Eesti" },
    { insert: " " },
    { attributes: { start: "175.96", end: "176.71" }, insert: "lahku" },
    { insert: " " },
    { attributes: { start: "177.19", end: "177.46" }, insert: "oma" },
    { insert: " " },
    {
      attributes: { start: "177.46", end: "178.84" },
      insert: "õiglusriikluse"
    },
    { insert: " " },
    {
      attributes: { start: "178.84", end: "179.83" },
      insert: "printsiipidest."
    },
    { insert: " " },
    { attributes: { start: "180.49", end: "180.7" }, insert: "Need" },
    { insert: " " },
    { attributes: { start: "180.7", end: "180.79" }, insert: "ei" },
    { insert: " " },
    { attributes: { start: "180.79", end: "181.15" }, insert: "vasta" },
    { insert: " " },
    { attributes: { start: "181.15", end: "181.6" }, insert: "tõele." },
    { insert: " \n" },
    { insert: { speaker: "Janek Salme" } },
    { attributes: { start: "182.15", end: "182.81" }, insert: "Heakskiidetud" },
    { insert: " " },
    { attributes: { start: "182.81", end: "183.08" }, insert: "leppes" },
    { insert: " " },
    { attributes: { start: "183.08", end: "183.53" }, insert: "lubatakse" },
    { insert: " " },
    { attributes: { start: "183.53", end: "183.68" }, insert: "muu" },
    { insert: " " },
    { attributes: { start: "183.68", end: "183.95" }, insert: "hulgas" },
    { insert: " " },
    { attributes: { start: "184.01", end: "184.25" }, insert: "läbi" },
    { insert: " " },
    { attributes: { start: "184.25", end: "184.55" }, insert: "viia" },
    { insert: " " },
    { attributes: { start: "184.55", end: "185" }, insert: "pensioni" },
    { insert: " " },
    { attributes: { start: "185", end: "185.24" }, insert: "teise" },
    { insert: " " },
    { attributes: { start: "185.24", end: "185.54" }, insert: "samba" },
    { insert: " " },
    { attributes: { start: "185.54", end: "186.02" }, insert: "reformi" },
    { insert: " " },
    { attributes: { start: "186.02", end: "186.11" }, insert: "ja" },
    { insert: " " },
    { attributes: { start: "186.11", end: "186.44" }, insert: "võtta" },
    { insert: " " },
    { attributes: { start: "186.44", end: "186.68" }, insert: "selle" },
    { insert: " " },
    { attributes: { start: "186.68", end: "186.95" }, insert: "aasta" },
    { insert: " " },
    { attributes: { start: "186.95", end: "187.16" }, insert: "sees" },
    { insert: " " },
    { attributes: { start: "187.16", end: "187.49" }, insert: "vastu" },
    { insert: " " },
    { attributes: { start: "187.49", end: "188.03" }, insert: "vajalikud" },
    { insert: " " },
    {
      attributes: { start: "188.06", end: "189.05" },
      insert: "seadusemuudatused."
    },
    { insert: " " },
    { attributes: { start: "189.71", end: "190.07" }, insert: "Isamaa" },
    { insert: " " },
    { attributes: { start: "190.07", end: "190.46" }, insert: "esimehe" },
    { insert: " " },
    { attributes: { start: "190.52", end: "191.24" }, insert: "Helir-Valdor" },
    { insert: " " },
    { attributes: { start: "191.27", end: "191.66" }, insert: "Seederi" },
    { insert: " " },
    { attributes: { start: "191.66", end: "191.96" }, insert: "sõnul" },
    { insert: " " },
    { attributes: { start: "191.99", end: "192.62" }, insert: "realiseerus" },
    { insert: " " },
    { attributes: { start: "192.68", end: "192.98" }, insert: "nende" },
    { insert: " " },
    { attributes: { start: "192.98", end: "193.13" }, insert: "üks" },
    { insert: " " },
    { attributes: { start: "193.13", end: "193.52" }, insert: "peamisi" },
    { insert: " " },
    {
      attributes: { start: "193.52", end: "194.39" },
      insert: "valimislubadusi"
    },
    { insert: " " },
    {
      attributes: { start: "194.42", end: "195.29" },
      insert: "koalitsioonileppes"
    },
    { insert: " " },
    { attributes: { start: "195.29", end: "195.62" }, insert: "umbes" },
    { insert: " " },
    { attributes: { start: "195.65", end: "196.25" }, insert: "90" },
    { insert: " " },
    { attributes: { start: "196.25", end: "196.7" }, insert: "protsendi" },
    { insert: " " },
    { attributes: { start: "196.7", end: "197.24" }, insert: "ulatuses." },
    { insert: " \n" }
  ]
};

module.exports = testContent;
